development: &development
  host: <%= ENV.fetch("ELASTICSEARCH_URL", "localhost:9200") %>
  prefix: stripe_test_development

test:
  <<: *development
  prefix: stripe_test_test

production:
  host: <%= ENV["BONSAI_URL"] %>
